In [2]:
import numpy as np

# 1. **Creating Arrays**
array1 = np.array([1, 2, 3])  # 1D array
array2 = np.array([[1, 2], [3, 4]])  # 2D array
array3 = np.zeros((2, 3))  # Array of zeros
array4 = np.ones((3, 3))  # Array of ones
array5 = np.empty((2, 2))  # Empty array (random values)

print("Arrays:")
print(array1)
print(array2)
print(array3)
print(array4)
print(array5)

Arrays:
[1 2 3]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[2.12199579e-314 1.20953760e-311]
 [4.80231808e-321 3.79442416e-321]]


In [3]:
# 2. **Array Attributes**
a = np.arange(15).reshape(3, 5)
print("\nArray Attributes:")
print("Shape:", a.shape)  # (3, 5)
print("Number of Dimensions:", a.ndim)  # Number of dimensions (axes)
print("Data Type:", a.dtype.name)  # Data type of elements
print("Size:", a.size)  # Total number of elements
print("Item Size:", a.itemsize)  # Size in bytes of each element
print("Type:", type(a))  # Type of array object


Array Attributes:
Shape: (3, 5)
Number of Dimensions: 2
Data Type: int32
Size: 15
Item Size: 4
Type: <class 'numpy.ndarray'>


In [4]:
# 3. **Creating Arrays with Specific Ranges**
b = np.arange(10)**3  # Cubes of numbers 0-9
print("\nArray Operations:")
print("Original Array:", b)
print("Slicing (2:5):", b[2:5])  # Slicing, elements 2 to 4
print("Reversed Array:", b[::-1])  # Reverse array

# Applying functions element-wise
for i in b:
    print(i**(1/3))  # Cube roots


Array Operations:
Original Array: [  0   1   8  27  64 125 216 343 512 729]
Slicing (2:5): [ 8 27 64]
Reversed Array: [729 512 343 216 125  64  27   8   1   0]
0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [5]:
# 4. **Mathematical Operations on Arrays**
B = np.arange(3)
C = np.array([2., -1., 4.])

print("\nMathematical Operations:")
print("Exp:", np.exp(B))  # Exponential
print("Sqrt:", np.sqrt(B))  # Square root
print("Add:", np.add(B, C))  # Add arrays element-wise


Mathematical Operations:
Exp: [1.         2.71828183 7.3890561 ]
Sqrt: [0.         1.         1.41421356]
Add: [2. 0. 6.]


In [6]:
# 5. **Aggregation Functions**
b = np.arange(12).reshape(3, 4)

print("\nAggregation Functions:")
print("Sum of Columns:", b.sum(axis=0))  # Sum of each column
print("Min of Rows:", b.min(axis=1))  # Min of each row
print("Cumulative Sum along Rows:", b.cumsum(axis=1))  # Cumulative sum along each row


Aggregation Functions:
Sum of Columns: [12 15 18 21]
Min of Rows: [0 4 8]
Cumulative Sum along Rows: [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [7]:
# 6. **Random Numbers with NumPy**
rg = np.random.default_rng(1)  # Random generator
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))  # Random values between 0 and 1
a *= 3
b += a
print("\nRandom Numbers and Operations:")
print("Random Array b:", b)


Random Numbers and Operations:
Random Array b: [[3.51182162 3.9504637  3.14415961]
 [3.94864945 3.31183145 3.42332645]]


In [8]:
# 7. **Array Manipulation**
a = np.floor(10 * rg.random((3, 4)))  # Random array with values floored
print("\nArray Manipulation:")
print("Flattened Array:", a.ravel())  # Flatten the array
print("Reshaped Array (6x2):", a.reshape(6, 2))  # Reshape the array to 6x2

a.resize((2, 6))  # Resize the array in-place
print("Resized Array:", a)


Array Manipulation:
Flattened Array: [8. 4. 5. 0. 7. 5. 3. 7. 3. 4. 1. 4.]
Reshaped Array (6x2): [[8. 4.]
 [5. 0.]
 [7. 5.]
 [3. 7.]
 [3. 4.]
 [1. 4.]]
Resized Array: [[8. 4. 5. 0. 7. 5.]
 [3. 7. 3. 4. 1. 4.]]


In [9]:
# 8. **Broadcasting (Array Operations)**
a = np.arange(3)
b = np.array([2., -1., 4.])
print("\nBroadcasting Operations:")
print("Broadcasted Addition:", a + b)  # Broadcasted addition


Broadcasting Operations:
Broadcasted Addition: [2. 0. 6.]


In [10]:
# 9. **Indexing and Slicing**
c = np.arange(10)
print("\nIndexing and Slicing:")
print("Slicing (2:5):", c[2:5])  # Slicing specific elements
print("Every Second Element:", c[::2])  # Every second element

d = np.fromfunction(lambda x, y: 10*x + y, (5, 4), dtype=int)
print("Multidimensional Indexing:")
print("Rows 1 to 2, all columns:", d[1:3, :])
print("All rows, column 1:", d[:, 1])


Indexing and Slicing:
Slicing (2:5): [2 3 4]
Every Second Element: [0 2 4 6 8]
Multidimensional Indexing:
Rows 1 to 2, all columns: [[10 11 12 13]
 [20 21 22 23]]
All rows, column 1: [ 1 11 21 31 41]


In [11]:
# 10. **Linear Algebra Operations**
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])
print("\nLinear Algebra Operations:")
print("Matrix Product (A.B):", np.dot(A, B))  # Matrix product
print("Transpose of A:", A.T)  # Transpose of matrix A


Linear Algebra Operations:
Matrix Product (A.B): [[5 4]
 [3 4]]
Transpose of A: [[1 0]
 [1 1]]


In [12]:
# 11. **Statistical Functions**
data = np.array([[1, 2], [3, 4], [5, 6]])
print("\nStatistical Functions:")
print("Mean:", np.mean(data))  # Mean of all elements
print("Median:", np.median(data))  # Median of all elements
print("Std Dev:", np.std(data))  # Standard deviation


Statistical Functions:
Mean: 3.5
Median: 3.5
Std Dev: 1.707825127659933


In [13]:
# 12. **Sorting and Searching**
arr = np.array([3, 1, 2, 4])
print("\nSorting and Searching:")
print("Sorted Array:", np.sort(arr))  # Sort the array
print("Sorted Indices:", np.argsort(arr))  # Return indices of the sorted elements
print("Index of Max:", np.argmax(arr))  # Index of the maximum value
print("Index of Min:", np.argmin(arr))  # Index of the minimum value


Sorting and Searching:
Sorted Array: [1 2 3 4]
Sorted Indices: [1 2 0 3]
Index of Max: 3
Index of Min: 1


In [14]:
# 13. **Element-wise Functions**
arr = np.array([1, 2, 3, 4, 5])
print("\nElement-wise Functions:")
print("Clipped Array:", np.clip(arr, 2, 4))  # Clip values outside the range [2, 4]

# Logical operations
arr2 = np.array([True, False, True])
print("All True:", np.all(arr2))  # Check if all elements are True
print("Any True:", np.any(arr2))  # Check if any element is True


Element-wise Functions:
Clipped Array: [2 2 3 4 4]
All True: False
Any True: True


In [15]:
# 14. **Advanced Array Manipulation**
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("\nAdvanced Array Manipulation:")
print("Outer Product:", np.outer(a, b))  # Outer product
print("Cumulative Sum:", np.cumsum(a))  # Cumulative sum
print("Cumulative Product:", np.cumprod(a))  # Cumulative product


Advanced Array Manipulation:
Outer Product: [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Cumulative Sum: [1 3 6]
Cumulative Product: [1 2 6]


In [16]:
# 15. **Covariance and Correlation**
data = np.array([[1, 2], [3, 4], [5, 6]])
print("\nCovariance and Correlation:")
print("Covariance Matrix:", np.cov(data.T))  # Covariance matrix
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print("Correlation Matrix:", np.corrcoef(x, y))  # Correlation matrix


Covariance and Correlation:
Covariance Matrix: [[4. 4.]
 [4. 4.]]
Correlation Matrix: [[1. 1.]
 [1. 1.]]


In [17]:
# 16. **Handling Missing Data**
arr = np.array([1, np.nan, 2, np.nan, 3])
print("\nHandling Missing Data:")
print("NaN Check:", np.isnan(arr))  # Check for NaNs
print("Mean Ignoring NaNs:", np.nanmean(arr))  # Mean ignoring NaNs


Handling Missing Data:
NaN Check: [False  True False  True False]
Mean Ignoring NaNs: 2.0


In [18]:
# 17. **Vectorization**
def myfunc(x, y):
    return x + y

vectorized_func = np.vectorize(myfunc)
print("\nVectorization:")
print("Vectorized Function:", vectorized_func([1, 2, 3], [4, 5, 6]))  # Apply to arrays


Vectorization:
Vectorized Function: [5 7 9]


In [19]:
# 18. **Advanced Indexing**
arr = np.arange(10)
indices = np.array([2, 5, 8])
print("\nAdvanced Indexing:")
print("Indexed Array:", arr[indices])  # Index with an array


Advanced Indexing:
Indexed Array: [2 5 8]


In [20]:
# 19. **Saving and Loading Data**
np.save('my_array.npy', a)
loaded_array = np.load('my_array.npy')
print("\nSaving and Loading Data:")
print("Loaded Array:", loaded_array)


Saving and Loading Data:
Loaded Array: [1 2 3]


In [2]:
# Practice Questions

In [22]:
# Create a 2D NumPy array of shape (3, 4) filled with random integers between 10 and 50. Find:

# The sum of all elements
# The maximum value in each column
# The minimum value in each row

import numpy as np
import random 

arr=np.random.randint(10,50,size=12).reshape(3,4)
print(arr)

ad=np.sum(arr)
print(ad)

maxi=np.max(arr,axis=0)
print(maxi)

mini=np.min(arr,axis=1)
print(mini)

[[34 15 49 23]
 [35 37 44 19]
 [44 37 44 11]]
392
[44 37 49 23]
[15 19 11]


In [23]:
# arr = np.array([[1, 2, 3, 4],
#                 [5, 6, 7, 8],
#                 [9, 10, 11, 12]])

# Extract the second row.
# Extract the third column.
# Extract the sub-array [[6, 7], [10, 11]].

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr[1,])
print(arr[:,2])
sub=arr[1:3,1:3]
print(sub)

[5 6 7 8]
[ 3  7 11]
[[ 6  7]
 [10 11]]


In [24]:
# a = np.array([1, 2, 3])
# b = np.array([4, 5, 6])
# Add a and b element-wise.
# Multiply each element of a by b.

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a+b)
a*=b
print(a)

[5 7 9]
[ 4 10 18]


In [25]:
# arr = np.arange(20).reshape(4, 5)
# Select all elements from the second column.
# Select all rows where the element in the first column is greater than or equal to 5.

arr = np.arange(20).reshape(4, 5)
print(arr)
print(arr[:,1])
print(arr[arr[:, 0] >= 5])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[ 1  6 11 16]
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [26]:
# arr = np.array([1, 2, 3, 4, 5, 6])
# Reshape it into a (2, 3) matrix.
# Flatten the matrix back to a 1D array.
# Transpose a reshaped version of the array into shape (3, 2).

arr = np.array([1, 2, 3, 4, 5, 6])
arr= arr.reshape(2,3)
arr=arr.ravel()
arr= arr.reshape(3,2).T
arr

array([[1, 3, 5],
       [2, 4, 6]])